### PR TITLE
TypeScript rewrite

### PR DESCRIPTION
**Pull request by Wedvich**
This PR is the culmination of the work done in #28 (TypeScript rewrite).

The current fork is now at its third iteration, and I'd like to get it back into the main repo now to ensure it's stable. Major points:

- The codebase has been rewritten in TypeScript from scratch and split into modules, to provide a better development experience and easier maintenance and extendability.
- The documentation was outdated and didn't match the current API surface (0.0.18). It has been rewritten from scratch along with the codebase to accurately cover the functionality that's available.
- The code now has 100% unit test coverage ([Coveralls.io](https://coveralls.io/github/Wedvich/structured-log)), providing confidence that we won't accidentally break anything major.
- The Bower package simply consists of the `bower.json` file in the same repo as the rest of the code, and will be automagically updated when we release new versions. There's still some work to be done (build a minified version, ignore more unnecessary files), but a functional example can be found in a temporary package on Bower now - `bower install structured-log-alpha#0.1.0-alpha`

Remaining work:

- [ ] Document upgrade path for those using 0.0.18. There's parity for the most part, but it's unrealistic that there won't be any breaking changes.
- [ ] Create typings that can be used for third-party sinks written in TypeScript.
  - Manual at first, but should be able to automate later.
- [ ] Create technical documentation for the public API surface.
  - Should be able to generate this automatically from JSDoc comments as well.
- [x] Potentially implement additional features that are nice to have, or that have been unintentionally removed as part of the rewrite.

So, please have a look! There's not much left of the old stuff, but there's plenty of new stuff to scrutinize!

### CODE REVIEW

**Comment by nblumhardt** [comment]
Beautiful! 🎉 :-)

@ashleydavis what do you think about this? Is a full switch to TypeScript (i.e. a merge) lined up with where you see the project going, or would a side-by-side implementation (e.g. `structured-log/structured-log-ts` or some nicer name) be preferable?

My time to contribute to this project is severely limited, so I don't feel I have enough skin in the game to make this kind of call, but FWIW I think the switch to TS might bring a bit more energy to the project, so despite the loss of some nice JavaScript 😢 I would support the merge. Depending of course on Martin's continued enthusiasm to push it forward :-)

Thoughts?

🎉 either way!!

**Comment by nblumhardt** [comment]
(Just wanted to make sure the discussion covered this specifically, since I notice there's no comment from @ashleydavis on the original issue ticket since the ES6 port was discussed.)

**Comment by Wedvich** [comment]
Yup, good call!

Just to clear up any confusion, in case there is any: the output is still meant to be consumed by JavaScript-based applications, and has both ES5 and ES6 versions that can be used. So this rewrite does not retarget the library to TypeScript-based clients. With that said, TS clients can obviously use the library as well, and I think the typings would be beneficial for future extensions to enable static type checking for compatibility with the base library.

I'm very interested in continuing to build on this and hopefully help it gain some more traction. A large part of the motivation for this rewrite was to split up the code to make it easier to understand, test, maintain and extend. I found the existing codebase difficult to reason about as almost everything is in a single source file. There was some mention of changing this in #17, but apart from that this was still in the open.

I think going forward with this rewritten codebase will make it easier for new contributors to jump in, and easier to write and verify 3rd party sinks (which don't need to be written in TypeScript, of course).

**Comment by nblumhardt** [comment]
Chatted briefly offline to @ashleydavis briefly (we're in the same city :-) ) and confirmed he's short on time as I am, but enthusiastic about seeing the project move forwards.

@Wedvich I've added you to the Reviewers (committers) team so you should be able to sort out any build/publishing issues that might appear post-merge, and can review/merge other PRs as they come along.

If you need any additional access/info please let me know (my username at my username .com will also reach me).

Do you want to address any of the remaining checkbox items pre-merge, or should we hit the button? :-)

**Comment by Wedvich** [comment]
Awesome! There's still a few bits of the docs I want to update and verify before going through with the merge, but hoping to get it done this weekend.

**Comment by Wedvich** [comment]
Allright, it's time to go ahead with the merge I think. Pushing the fun button!

**Pull request merged**
