### PR TITLE
Serilog compact json console sink

### PR DESCRIPTION
**Pull request by andymac4182**
The plan for this is to write out json to console that matches what can be sent to Seq. 

Design based on https://github.com/serilog/serilog-formatting-compact/blob/dev/README.md#format-details

### CODE REVIEW

**Comment by andymac4182** [comment]
@ashleydavis Should I be using `dev` or `master` as base?

**Comment by ashleydavis** [comment]
Hi Andrew,

Looks good.

The use of 'Reified properties' are interesting and in the future we should probably move those to the core code.

Do you think that 'serilog-compact-console-sink.js' is the right name? Should it be simply be called 'json-console-sink'?

Cheers
Ash

**Comment by andymac4182** [comment]
@ashleydavis I was thinking of including a second sink that wrote the event object straight to console which would be called `json-console-sink`. I named this one to match the name from serilog and seq as that is what it is designed to work with. 

I am not sure how to get the tests to pass. I am using Node 4.4.7 and they all pass. If you could let me know what I am doing wrong that would be great as I haven't used Node 0.10 in a long time.

**Comment by nblumhardt** [comment]
>  I named this one to match the name from serilog and seq as that is what it is designed to work with.

FWIW I'm hoping the format serves more than just Serilog/Seq at some point; there's a Rust implementation in https://github.com/emit-rs/emit/blob/master/src/formatters/json/mod.rs for example. Would `compact-json-console-sink` do the trick?

(Alternatively, or in future, accepting a `formatter` argument to `consoleSink()` would be a nice factoring.)

**Comment by andymac4182** [comment]
@nblumhardt That sounds good for now. I will look at refactoring out the formatters to be an argument for console sink as I am about to do the same to write to seq directly via http for another use case.

**Pull request merged**
