### PR TITLE
Pass event to Enricher so that properties can be overwritten

### PR DESCRIPTION
**Pull request by lyallaward**
When logging details of actions from external frameworks, the action information may include sensitive data. With this change a custom enricher can be used to modify the event properties and prevent sensitive data from being logged.

Small changes were also required to get the tests to work locally.

### CODE REVIEW

**Comment by Wedvich** [comment]
Thanks @lyallaward ! Will merge and pump out another release!

**Comment by Wedvich** [comment]
@lyallaward I should probably have asked this before merging, but... do you have a usage example?

**Comment by lyallaward** [comment]
Thanks @Wedvich I'll send another PR with a usage example in the tests.

**Comment by lyallaward** [comment]
Hi @Wedvich have you had a chance to look at that other PR, I know a project that is eagerly awaiting the next version of structured-log

**Comment by Wedvich** [comment]
Hi, sorry about the delay, I've been swamped with work lately! I'll merge
it in and prepare a new release tonight.

20. sep. 2017 01:29 skrev "Lyall" <notifications@github.com>:

**Comment by Wedvich** [comment]
@lyallaward Released this as part of v0.2.0 now. I opted to pass a clone of the event properties rather than a reference to the event object, so the syntax is slightly different from your example - but have a look and check if it suits your needs! There's an example in the README and in the unit tests of how it works live now.

Sorry again for being so slow to push this one out!

**Comment by lyallaward** [comment]
Thanks @Wedvich looks great. Appreciate all the input and the clone looks fine, I only left that out as I wasn't sure about how concerned you would be about the memory usage.

**Pull request merged**
